import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SidebarProvider } from "@/components/ui/sidebar";
import { PostcomSidebar } from "@/components/postcom-sidebar";
import { AuthProvider } from "@/context/AuthContext";

const instaMedium = localFont({
  src: "../fonts/InstagramSansMedium.woff",
  variable: "--font-insta-sans",
  weight: "100 900",
});

const instaMono = localFont({
  src: "../fonts/InstagramSans.woff",
  variable: "--font-insta-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instaMedium.variable} ${instaMono.variable} antialiased`}
      >
        <div className="mx-auto max-w-7xl bg-background">
          <AuthProvider>
            <SidebarProvider>
              <div className="flex min-h-screen">
                <PostcomSidebar />
                <main className="flex-1 ">
                  <div className="mx-auto max-w-2xl">{children}</div>
                </main>
                {/* <div className="hidden w-[348px] lg:block" /> */}
              </div>
              <Toaster />
            </SidebarProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
