import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head />
//       <body>
//         <main>{children}</main>
//       </body>
//     </html>
//   )
// }


const instaMedium = localFont({
  src: "./fonts/InstagramSansMedium.woff",
  variable: "--font-insta-sans",
  weight: "100 900",
});
const instaMono = localFont({
  src: "./fonts/InstagramSans.woff",
  variable: "--font-insta-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instaMedium.variable} ${instaMono.variable} antialiased`}
      >
        <main>{children}</main>
        <Toaster />

      </body>
    </html>
  );
}
